apiVersion: v2
name: bitwarden
description: Bitwarden chart
type: application
version: 0.1.0
appVersion: "1.23.1"
dependencies:
- name: bitwarden-k8s
  version: 0.1.5
  repository: https://cdwv.github.io/bitwarden-k8s/
