apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - name: http
              protocol: TCP
              containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config/
          env:
            - name: TZ
              value: America/Sao_Paulo
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc
