apiVersion: v2
name: jellyfin
description: Jellyfin chart
type: application
version: 0.1.0
dependencies:
- name: csi-driver-smb
  version: 1.10.0
  repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
- name: jellyfin
  version: 0.3.0
  repository: https://github.com/brianmcarey/jellyfin-helm.git
