csi-driver-smb:
  controller:
    dnsPolicy: ClusterFirstWithHostNet
  linux:
    dnsPolicy: ClusterFirstWithHostNet
jellyfin:
  image:
    tag: "latest"
  persistence:
    config:
      enabled: false
      ## jellyfin configuration data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      ##
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      existingClaim: pvc-smb
      subPath: config
      accessMode: ReadWriteOnce
      size: 1Gi
    media:
      enabled: false
      ## Directory where media is persisted
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      ##
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      existingClaim: pvc-smb
      subPath: test
      accessMode: ReadWriteOnce
      size: 10Gi
